name: Taskwarrior WebUI
version: "1.0.0"
slug: taskwarrior_webui
description: Taskwarrior Web UI

arch:
  - amd64
  - aarch64

startup: services
boot: auto

ingress: true
ingress_port: 80

ports:
  80/tcp: 80

map:
  - config:rw

options: {}

schema: {}